INSERT INTO language(id,name,nativename,code) VALUES (0,'Northwest Caucasian','Abkhaz','ab');
INSERT INTO language(id,name,nativename,code) VALUES (1,'Afro-Asiatic','Afar','aa');
INSERT INTO language(id,name,nativename,code) VALUES (2,'Indo-European','Afrikaans','af');
INSERT INTO language(id,name,nativename,code) VALUES (3,'Niger-Congo','Akan','ak');
INSERT INTO language(id,name,nativename,code) VALUES (4,'Indo-European','Albanian','sq');
INSERT INTO language(id,name,nativename,code) VALUES (5,'Afro-Asiatic','Amharic','am');
INSERT INTO language(id,name,nativename,code) VALUES (6,'Afro-Asiatic','Arabic','ar');
INSERT INTO language(id,name,nativename,code) VALUES (7,'Indo-European','Aragonese','an');
INSERT INTO language(id,name,nativename,code) VALUES (8,'Indo-European','Armenian','hy');
INSERT INTO language(id,name,nativename,code) VALUES (9,'Indo-European','Assamese','as');
INSERT INTO language(id,name,nativename,code) VALUES (10,'Northeast Caucasian','Avaric','av');
INSERT INTO language(id,name,nativename,code) VALUES (11,'Indo-European','Avestan','ae');
INSERT INTO language(id,name,nativename,code) VALUES (12,'Aymaran','Aymara','ay');
INSERT INTO language(id,name,nativename,code) VALUES (13,'Turkic','Azerbaijani','az');
INSERT INTO language(id,name,nativename,code) VALUES (14,'Niger-Congo','Bambara','bm');
INSERT INTO language(id,name,nativename,code) VALUES (15,'Turkic','Bashkir','ba');
INSERT INTO language(id,name,nativename,code) VALUES (16,'Language isolate','Basque','eu');
INSERT INTO language(id,name,nativename,code) VALUES (17,'Indo-European','Belarusian','be');
INSERT INTO language(id,name,nativename,code) VALUES (18,'Indo-European','Bengali, Bangla','bn');
INSERT INTO language(id,name,nativename,code) VALUES (19,'Indo-European','Bihari','bh');
INSERT INTO language(id,name,nativename,code) VALUES (20,'Creole','Bislama','bi');
INSERT INTO language(id,name,nativename,code) VALUES (21,'Indo-European','Bosnian','bs');
INSERT INTO language(id,name,nativename,code) VALUES (22,'Indo-European','Breton','br');
INSERT INTO language(id,name,nativename,code) VALUES (23,'Indo-European','Bulgarian','bg');
INSERT INTO language(id,name,nativename,code) VALUES (24,'Sino-Tibetan','Burmese','my');
INSERT INTO language(id,name,nativename,code) VALUES (25,'Indo-European','Catalan','ca');
INSERT INTO language(id,name,nativename,code) VALUES (26,'Austronesian','Chamorro','ch');
INSERT INTO language(id,name,nativename,code) VALUES (27,'Northeast Caucasian','Chechen','ce');
INSERT INTO language(id,name,nativename,code) VALUES (28,'Niger-Congo','Chichewa, Chewa, Nyanja','ny');
INSERT INTO language(id,name,nativename,code) VALUES (29,'Sino-Tibetan','Chinese','zh');
INSERT INTO language(id,name,nativename,code) VALUES (30,'Turkic','Chuvash','cv');
INSERT INTO language(id,name,nativename,code) VALUES (31,'Indo-European','Cornish','kw');
INSERT INTO language(id,name,nativename,code) VALUES (32,'Indo-European','Corsican','co');
INSERT INTO language(id,name,nativename,code) VALUES (33,'Algonquian','Cree','cr');
INSERT INTO language(id,name,nativename,code) VALUES (34,'Indo-European','Croatian','hr');
INSERT INTO language(id,name,nativename,code) VALUES (35,'Indo-European','Czech','cs');
INSERT INTO language(id,name,nativename,code) VALUES (36,'Indo-European','Danish','da');
INSERT INTO language(id,name,nativename,code) VALUES (37,'Indo-European','Divehi, Dhivehi, Maldivian','dv');
INSERT INTO language(id,name,nativename,code) VALUES (38,'Indo-European','Dutch','nl');
INSERT INTO language(id,name,nativename,code) VALUES (39,'Sino-Tibetan','Dzongkha','dz');
INSERT INTO language(id,name,nativename,code) VALUES (40,'Indo-European','English','en');
INSERT INTO language(id,name,nativename,code) VALUES (41,'Constructed','Esperanto','eo');
INSERT INTO language(id,name,nativename,code) VALUES (42,'Uralic','Estonian','et');
INSERT INTO language(id,name,nativename,code) VALUES (43,'Niger-Congo','Ewe','ee');
INSERT INTO language(id,name,nativename,code) VALUES (44,'Indo-European','Faroese','fo');
INSERT INTO language(id,name,nativename,code) VALUES (45,'Austronesian','Fijian','fj');
INSERT INTO language(id,name,nativename,code) VALUES (46,'Uralic','Finnish','fi');
INSERT INTO language(id,name,nativename,code) VALUES (47,'Indo-European','French','fr');
INSERT INTO language(id,name,nativename,code) VALUES (48,'Niger-Congo','Fula, Fulah, Pulaar, Pular','ff');
INSERT INTO language(id,name,nativename,code) VALUES (49,'Indo-European','Galician','gl');
INSERT INTO language(id,name,nativename,code) VALUES (50,'South Caucasian','Georgian','ka');
INSERT INTO language(id,name,nativename,code) VALUES (51,'Indo-European','German','de');
INSERT INTO language(id,name,nativename,code) VALUES (52,'Indo-European','Greek?(modern)','el');
INSERT INTO language(id,name,nativename,code) VALUES (53,'Tupian','Guaran?','gn');
INSERT INTO language(id,name,nativename,code) VALUES (54,'Indo-European','Gujarati','gu');
INSERT INTO language(id,name,nativename,code) VALUES (55,'Creole','Haitian, Haitian Creole','ht');
INSERT INTO language(id,name,nativename,code) VALUES (56,'Afro-Asiatic','Hausa','ha');
INSERT INTO language(id,name,nativename,code) VALUES (57,'Afro-Asiatic','Hebrew?(modern)','he');
INSERT INTO language(id,name,nativename,code) VALUES (58,'Niger-Congo','Herero','hz');
INSERT INTO language(id,name,nativename,code) VALUES (59,'Indo-European','Hindi','hi');
INSERT INTO language(id,name,nativename,code) VALUES (60,'Austronesian','Hiri Motu','ho');
INSERT INTO language(id,name,nativename,code) VALUES (61,'Uralic','Hungarian','hu');
INSERT INTO language(id,name,nativename,code) VALUES (62,'Constructed','Interlingua','ia');
INSERT INTO language(id,name,nativename,code) VALUES (63,'Austronesian','Indonesian','id');
INSERT INTO language(id,name,nativename,code) VALUES (64,'Constructed','Interlingue','ie');
INSERT INTO language(id,name,nativename,code) VALUES (65,'Indo-European','Irish','ga');
INSERT INTO language(id,name,nativename,code) VALUES (66,'Niger-Congo','Igbo','ig');
INSERT INTO language(id,name,nativename,code) VALUES (67,'Eskimo-Aleut','Inupiaq','ik');
INSERT INTO language(id,name,nativename,code) VALUES (68,'Constructed','Ido','io');
INSERT INTO language(id,name,nativename,code) VALUES (69,'Indo-European','Icelandic','is');
INSERT INTO language(id,name,nativename,code) VALUES (70,'Indo-European','Italian','it');
INSERT INTO language(id,name,nativename,code) VALUES (71,'Eskimo-Aleut','Inuktitut','iu');
INSERT INTO language(id,name,nativename,code) VALUES (72,'Japonic','Japanese','ja');
INSERT INTO language(id,name,nativename,code) VALUES (73,'Austronesian','Javanese','jv');
INSERT INTO language(id,name,nativename,code) VALUES (74,'Eskimo-Aleut','Kalaallisut, Greenlandic','kl');
INSERT INTO language(id,name,nativename,code) VALUES (75,'Dravidian','Kannada','kn');
INSERT INTO language(id,name,nativename,code) VALUES (76,'Nilo-Saharan','Kanuri','kr');
INSERT INTO language(id,name,nativename,code) VALUES (77,'Indo-European','Kashmiri','ks');
INSERT INTO language(id,name,nativename,code) VALUES (78,'Turkic','Kazakh','kk');
INSERT INTO language(id,name,nativename,code) VALUES (79,'Austroasiatic','Khmer','km');
INSERT INTO language(id,name,nativename,code) VALUES (80,'Niger-Congo','Kikuyu, Gikuyu','ki');
INSERT INTO language(id,name,nativename,code) VALUES (81,'Niger-Congo','Kinyarwanda','rw');
INSERT INTO language(id,name,nativename,code) VALUES (82,'Turkic','Kyrgyz','ky');
INSERT INTO language(id,name,nativename,code) VALUES (83,'Uralic','Komi','kv');
INSERT INTO language(id,name,nativename,code) VALUES (84,'Niger-Congo','Kongo','kg');
INSERT INTO language(id,name,nativename,code) VALUES (85,'Koreanic','Korean','ko');
INSERT INTO language(id,name,nativename,code) VALUES (86,'Indo-European','Kurdish','ku');
INSERT INTO language(id,name,nativename,code) VALUES (87,'Niger-Congo','Kwanyama, Kuanyama','kj');
INSERT INTO language(id,name,nativename,code) VALUES (88,'Indo-European','Latin','la');
INSERT INTO language(id,name,nativename,code) VALUES (89,'Indo-European','Luxembourgish, Letzeburgesch','lb');
INSERT INTO language(id,name,nativename,code) VALUES (90,'Niger-Congo','Ganda','lg');
INSERT INTO language(id,name,nativename,code) VALUES (91,'Indo-European','Limburgish, Limburgan, Limburger','li');
INSERT INTO language(id,name,nativename,code) VALUES (92,'Niger-Congo','Lingala','ln');
INSERT INTO language(id,name,nativename,code) VALUES (93,'Tai-Kadai','Lao','lo');
INSERT INTO language(id,name,nativename,code) VALUES (94,'Indo-European','Lithuanian','lt');
INSERT INTO language(id,name,nativename,code) VALUES (95,'Niger-Congo','Luba-Katanga','lu');
INSERT INTO language(id,name,nativename,code) VALUES (96,'Indo-European','Latvian','lv');
INSERT INTO language(id,name,nativename,code) VALUES (97,'Indo-European','Manx','gv');
INSERT INTO language(id,name,nativename,code) VALUES (98,'Indo-European','Macedonian','mk');
INSERT INTO language(id,name,nativename,code) VALUES (99,'Austronesian','Malagasy','mg');
INSERT INTO language(id,name,nativename,code) VALUES (100,'Austronesian','Malay','ms');
INSERT INTO language(id,name,nativename,code) VALUES (101,'Dravidian','Malayalam','ml');
INSERT INTO language(id,name,nativename,code) VALUES (102,'Afro-Asiatic','Maltese','mt');
INSERT INTO language(id,name,nativename,code) VALUES (103,'Austronesian','M-ori','mi');
INSERT INTO language(id,name,nativename,code) VALUES (104,'Indo-European','Marathi (Mar--h-)','mr');
INSERT INTO language(id,name,nativename,code) VALUES (105,'Austronesian','Marshallese','mh');
INSERT INTO language(id,name,nativename,code) VALUES (106,'Mongolic','Mongolian','mn');
INSERT INTO language(id,name,nativename,code) VALUES (107,'Austronesian','Nauruan','na');
INSERT INTO language(id,name,nativename,code) VALUES (108,'Den?-Yeniseian','Navajo, Navaho','nv');
INSERT INTO language(id,name,nativename,code) VALUES (109,'Niger-Congo','Northern Ndebele','nd');
INSERT INTO language(id,name,nativename,code) VALUES (110,'Indo-European','Nepali','ne');
INSERT INTO language(id,name,nativename,code) VALUES (111,'Niger-Congo','Ndonga','ng');
INSERT INTO language(id,name,nativename,code) VALUES (112,'Indo-European','Norwegian Bokm?l','nb');
INSERT INTO language(id,name,nativename,code) VALUES (113,'Indo-European','Norwegian Nynorsk','nn');
INSERT INTO language(id,name,nativename,code) VALUES (114,'Indo-European','Norwegian','no');
INSERT INTO language(id,name,nativename,code) VALUES (115,'Sino-Tibetan','Nuosu','ii');
INSERT INTO language(id,name,nativename,code) VALUES (116,'Niger-Congo','Southern Ndebele','nr');
INSERT INTO language(id,name,nativename,code) VALUES (117,'Indo-European','Occitan','oc');
INSERT INTO language(id,name,nativename,code) VALUES (118,'Algonquian','Ojibwe, Ojibwa','oj');
INSERT INTO language(id,name,nativename,code) VALUES (119,'Indo-European','Old Church Slavonic,?Church Slavonic,?Old Bulgarian','cu');
INSERT INTO language(id,name,nativename,code) VALUES (120,'Afro-Asiatic','Oromo','om');
INSERT INTO language(id,name,nativename,code) VALUES (121,'Indo-European','Oriya','or');
INSERT INTO language(id,name,nativename,code) VALUES (122,'Indo-European','Ossetian, Ossetic','os');
INSERT INTO language(id,name,nativename,code) VALUES (123,'Indo-European','Panjabi, Punjabi','pa');
INSERT INTO language(id,name,nativename,code) VALUES (124,'Indo-European','P-li','pi');
INSERT INTO language(id,name,nativename,code) VALUES (125,'Indo-European','Persian?(Farsi)','fa');
INSERT INTO language(id,name,nativename,code) VALUES (126,'Indo-European','Polish','pl');
INSERT INTO language(id,name,nativename,code) VALUES (127,'Indo-European','Pashto, Pushto','ps');
INSERT INTO language(id,name,nativename,code) VALUES (128,'Indo-European','Portuguese','pt');
INSERT INTO language(id,name,nativename,code) VALUES (129,'Quechuan','Quechua','qu');
INSERT INTO language(id,name,nativename,code) VALUES (130,'Indo-European','Romansh','rm');
INSERT INTO language(id,name,nativename,code) VALUES (131,'Niger-Congo','Kirundi','rn');
INSERT INTO language(id,name,nativename,code) VALUES (132,'Creole','Reunionese,?Reunion Creole','rc');
INSERT INTO language(id,name,nativename,code) VALUES (133,'Indo-European','Romanian','ro');
INSERT INTO language(id,name,nativename,code) VALUES (134,'Indo-European','Russian','ru');
INSERT INTO language(id,name,nativename,code) VALUES (135,'Indo-European','Sanskrit (Sa-sk-ta)','sa');
INSERT INTO language(id,name,nativename,code) VALUES (136,'Indo-European','Sardinian','sc');
INSERT INTO language(id,name,nativename,code) VALUES (137,'Indo-European','Sindhi','sd');
INSERT INTO language(id,name,nativename,code) VALUES (138,'Uralic','Northern Sami','se');
INSERT INTO language(id,name,nativename,code) VALUES (139,'Austronesian','Samoan','sm');
INSERT INTO language(id,name,nativename,code) VALUES (140,'Creole','Sango','sg');
INSERT INTO language(id,name,nativename,code) VALUES (141,'Indo-European','Serbian','sr');
INSERT INTO language(id,name,nativename,code) VALUES (142,'Indo-European','Scottish Gaelic, Gaelic','gd');
INSERT INTO language(id,name,nativename,code) VALUES (143,'Niger-Congo','Shona','sn');
INSERT INTO language(id,name,nativename,code) VALUES (144,'Indo-European','Sinhalese, Sinhala','si');
INSERT INTO language(id,name,nativename,code) VALUES (145,'Indo-European','Slovak','sk');
INSERT INTO language(id,name,nativename,code) VALUES (146,'Indo-European','Slovene','sl');
INSERT INTO language(id,name,nativename,code) VALUES (147,'Afro-Asiatic','Somali','so');
INSERT INTO language(id,name,nativename,code) VALUES (148,'Niger-Congo','Southern Sotho','st');
INSERT INTO language(id,name,nativename,code) VALUES (149,'Indo-European','Spanish','es');
INSERT INTO language(id,name,nativename,code) VALUES (150,'Austronesian','Sundanese','su');
INSERT INTO language(id,name,nativename,code) VALUES (151,'Niger-Congo','Swahili','sw');
INSERT INTO language(id,name,nativename,code) VALUES (152,'Niger-Congo','Swati','ss');
INSERT INTO language(id,name,nativename,code) VALUES (153,'Indo-European','Swedish','sv');
INSERT INTO language(id,name,nativename,code) VALUES (154,'Dravidian','Tamil','ta');
INSERT INTO language(id,name,nativename,code) VALUES (155,'Dravidian','Telugu','te');
INSERT INTO language(id,name,nativename,code) VALUES (156,'Indo-European','Tajik','tg');
INSERT INTO language(id,name,nativename,code) VALUES (157,'Tai-Kadai','Thai','th');
INSERT INTO language(id,name,nativename,code) VALUES (158,'Afro-Asiatic','Tigrinya','ti');
INSERT INTO language(id,name,nativename,code) VALUES (159,'Sino-Tibetan','Tibetan Standard, Tibetan, Central','bo');
INSERT INTO language(id,name,nativename,code) VALUES (160,'Turkic','Turkmen','tk');
INSERT INTO language(id,name,nativename,code) VALUES (161,'Austronesian','Tagalog','tl');
INSERT INTO language(id,name,nativename,code) VALUES (162,'Niger-Congo','Tswana','tn');
INSERT INTO language(id,name,nativename,code) VALUES (163,'Austronesian','Tonga?(Tonga Islands)','to');
INSERT INTO language(id,name,nativename,code) VALUES (164,'Turkic','Turkish','tr');
INSERT INTO language(id,name,nativename,code) VALUES (165,'Niger-Congo','Tsonga','ts');
INSERT INTO language(id,name,nativename,code) VALUES (166,'Turkic','Tatar','tt');
INSERT INTO language(id,name,nativename,code) VALUES (167,'Niger-Congo','Twi','tw');
INSERT INTO language(id,name,nativename,code) VALUES (168,'Austronesian','Tahitian','ty');
INSERT INTO language(id,name,nativename,code) VALUES (169,'Turkic','Uyghur','ug');
INSERT INTO language(id,name,nativename,code) VALUES (170,'Indo-European','Ukrainian','uk');
INSERT INTO language(id,name,nativename,code) VALUES (171,'Indo-European','Urdu','ur');
INSERT INTO language(id,name,nativename,code) VALUES (172,'Turkic','Uzbek','uz');
INSERT INTO language(id,name,nativename,code) VALUES (173,'Niger-Congo','Venda','ve');
INSERT INTO language(id,name,nativename,code) VALUES (174,'Austroasiatic','Vietnamese','vi');
INSERT INTO language(id,name,nativename,code) VALUES (175,'Constructed','Volap?k','vo');
INSERT INTO language(id,name,nativename,code) VALUES (176,'Indo-European','Walloon','wa');
INSERT INTO language(id,name,nativename,code) VALUES (177,'Indo-European','Welsh','cy');
INSERT INTO language(id,name,nativename,code) VALUES (178,'Niger-Congo','Wolof','wo');
INSERT INTO language(id,name,nativename,code) VALUES (179,'Indo-European','Western Frisian','fy');
INSERT INTO language(id,name,nativename,code) VALUES (180,'Niger-Congo','Xhosa','xh');
INSERT INTO language(id,name,nativename,code) VALUES (181,'Indo-European','Yiddish','yi');
INSERT INTO language(id,name,nativename,code) VALUES (182,'Niger-Congo','Yoruba','yo');
INSERT INTO language(id,name,nativename,code) VALUES (183,'Tai-Kadai','Zhuang, Chuang','za');
INSERT INTO language(id,name,nativename,code) VALUES (184,'Niger-Congo','Zulu','zu');
